name: Trivy scan

on:
  push:
    branches:
      - feature/sre-1405

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy_0.20.0_Linux-64bit.deb
        sudo apt install ./trivy_0.20.0_Linux-64bit.deb
    - name: Run Trivy vulnerability scanner in IaC mode
      run: |
         trivy  --severity HIGH,CRITICAL --ignore-unfixed .helm
      
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@312e093a1892bd801f026f1090904ee8e460b9b6 # v2.1.34
      with:
        sarif_file: 'trivy-results.sarif'
